/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: projects/smart_light_example/smart_light_example.proto */

#ifndef PROTOBUF_C_projects_2fsmart_5flight_5fexample_2fsmart_5flight_5fexample_2eproto__INCLUDED
#define PROTOBUF_C_projects_2fsmart_5flight_5fexample_2fsmart_5flight_5fexample_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif




/* --- enums --- */

typedef enum _Projects__SmartLightExample__Resource {
  PROJECTS__SMART_LIGHT_EXAMPLE__RESOURCE__RESOURCE_UNSPECIFIED = 0,
  PROJECTS__SMART_LIGHT_EXAMPLE__RESOURCE__RESOURCE_SET_LIGHT_RELAY = 1,
  PROJECTS__SMART_LIGHT_EXAMPLE__RESOURCE__RESOURCE_SET_NAME = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(PROJECTS__SMART_LIGHT_EXAMPLE__RESOURCE)
} Projects__SmartLightExample__Resource;

/* --- messages --- */

/* --- per-message closures --- */


/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    projects__smart_light_example__resource__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_projects_2fsmart_5flight_5fexample_2fsmart_5flight_5fexample_2eproto__INCLUDED */
