/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: projects/smart_light_example/smart_light_example.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "projects/smart_light_example/smart_light_example.pb-c.h"
static const ProtobufCEnumValue projects__smart_light_example__resource__enum_values_by_number[3] =
{
  { "RESOURCE_UNSPECIFIED", "PROJECTS__SMART_LIGHT_EXAMPLE__RESOURCE__RESOURCE_UNSPECIFIED", 0 },
  { "RESOURCE_SET_LIGHT_RELAY", "PROJECTS__SMART_LIGHT_EXAMPLE__RESOURCE__RESOURCE_SET_LIGHT_RELAY", 1 },
  { "RESOURCE_SET_NAME", "PROJECTS__SMART_LIGHT_EXAMPLE__RESOURCE__RESOURCE_SET_NAME", 2 },
};
static const ProtobufCIntRange projects__smart_light_example__resource__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex projects__smart_light_example__resource__enum_values_by_name[3] =
{
  { "RESOURCE_SET_LIGHT_RELAY", 1 },
  { "RESOURCE_SET_NAME", 2 },
  { "RESOURCE_UNSPECIFIED", 0 },
};
const ProtobufCEnumDescriptor projects__smart_light_example__resource__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "projects.smart_light_example.Resource",
  "Resource",
  "Projects__SmartLightExample__Resource",
  "projects.smart_light_example",
  3,
  projects__smart_light_example__resource__enum_values_by_number,
  3,
  projects__smart_light_example__resource__enum_values_by_name,
  1,
  projects__smart_light_example__resource__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
