/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: telemetry/telemetry.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "telemetry/telemetry.pb-c.h"
void   telemetry__sem_ver__init
                     (Telemetry__SemVer         *message)
{
  static const Telemetry__SemVer init_value = TELEMETRY__SEM_VER__INIT;
  *message = init_value;
}
size_t telemetry__sem_ver__get_packed_size
                     (const Telemetry__SemVer *message)
{
  assert(message->base.descriptor == &telemetry__sem_ver__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t telemetry__sem_ver__pack
                     (const Telemetry__SemVer *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &telemetry__sem_ver__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t telemetry__sem_ver__pack_to_buffer
                     (const Telemetry__SemVer *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &telemetry__sem_ver__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Telemetry__SemVer *
       telemetry__sem_ver__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Telemetry__SemVer *)
     protobuf_c_message_unpack (&telemetry__sem_ver__descriptor,
                                allocator, len, data);
}
void   telemetry__sem_ver__free_unpacked
                     (Telemetry__SemVer *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &telemetry__sem_ver__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   telemetry__record__init
                     (Telemetry__Record         *message)
{
  static const Telemetry__Record init_value = TELEMETRY__RECORD__INIT;
  *message = init_value;
}
size_t telemetry__record__get_packed_size
                     (const Telemetry__Record *message)
{
  assert(message->base.descriptor == &telemetry__record__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t telemetry__record__pack
                     (const Telemetry__Record *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &telemetry__record__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t telemetry__record__pack_to_buffer
                     (const Telemetry__Record *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &telemetry__record__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Telemetry__Record *
       telemetry__record__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Telemetry__Record *)
     protobuf_c_message_unpack (&telemetry__record__descriptor,
                                allocator, len, data);
}
void   telemetry__record__free_unpacked
                     (Telemetry__Record *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &telemetry__record__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   telemetry__telemetry_pack__init
                     (Telemetry__TelemetryPack         *message)
{
  static const Telemetry__TelemetryPack init_value = TELEMETRY__TELEMETRY_PACK__INIT;
  *message = init_value;
}
size_t telemetry__telemetry_pack__get_packed_size
                     (const Telemetry__TelemetryPack *message)
{
  assert(message->base.descriptor == &telemetry__telemetry_pack__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t telemetry__telemetry_pack__pack
                     (const Telemetry__TelemetryPack *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &telemetry__telemetry_pack__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t telemetry__telemetry_pack__pack_to_buffer
                     (const Telemetry__TelemetryPack *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &telemetry__telemetry_pack__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Telemetry__TelemetryPack *
       telemetry__telemetry_pack__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Telemetry__TelemetryPack *)
     protobuf_c_message_unpack (&telemetry__telemetry_pack__descriptor,
                                allocator, len, data);
}
void   telemetry__telemetry_pack__free_unpacked
                     (Telemetry__TelemetryPack *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &telemetry__telemetry_pack__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor telemetry__sem_ver__field_descriptors[3] =
{
  {
    "major",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Telemetry__SemVer, major),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "minor",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Telemetry__SemVer, minor),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "patch",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Telemetry__SemVer, patch),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned telemetry__sem_ver__field_indices_by_name[] = {
  0,   /* field[0] = major */
  1,   /* field[1] = minor */
  2,   /* field[2] = patch */
};
static const ProtobufCIntRange telemetry__sem_ver__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor telemetry__sem_ver__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "telemetry.SemVer",
  "SemVer",
  "Telemetry__SemVer",
  "telemetry",
  sizeof(Telemetry__SemVer),
  3,
  telemetry__sem_ver__field_descriptors,
  telemetry__sem_ver__field_indices_by_name,
  1,  telemetry__sem_ver__number_ranges,
  (ProtobufCMessageInit) telemetry__sem_ver__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor telemetry__record__field_descriptors[9] =
{
  {
    "resource",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Telemetry__Record, resource),
    &telemetry__resource__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "time",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Telemetry__Record, time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Telemetry__Record, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "string_value",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Telemetry__Record, string_value),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bool_value",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Telemetry__Record, bool_value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data_value",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Telemetry__Record, data_value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "severity",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Telemetry__Record, severity),
    &telemetry__severity__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "alert_id",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Telemetry__Record, alert_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "int_value",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Telemetry__Record, int_value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned telemetry__record__field_indices_by_name[] = {
  7,   /* field[7] = alert_id */
  4,   /* field[4] = bool_value */
  5,   /* field[5] = data_value */
  8,   /* field[8] = int_value */
  0,   /* field[0] = resource */
  6,   /* field[6] = severity */
  3,   /* field[3] = string_value */
  1,   /* field[1] = time */
  2,   /* field[2] = value */
};
static const ProtobufCIntRange telemetry__record__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 4, 1 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor telemetry__record__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "telemetry.Record",
  "Record",
  "Telemetry__Record",
  "telemetry",
  sizeof(Telemetry__Record),
  9,
  telemetry__record__field_descriptors,
  telemetry__record__field_indices_by_name,
  2,  telemetry__record__number_ranges,
  (ProtobufCMessageInit) telemetry__record__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor telemetry__telemetry_pack__field_descriptors[5] =
{
  {
    "records",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Telemetry__TelemetryPack, n_records),
    offsetof(Telemetry__TelemetryPack, records),
    &telemetry__record__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "base_resource",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Telemetry__TelemetryPack, base_resource),
    &telemetry__resource__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "base_time",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Telemetry__TelemetryPack, base_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "network_type",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Telemetry__TelemetryPack, network_type),
    &telemetry__network_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "network_id",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Telemetry__TelemetryPack, network_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned telemetry__telemetry_pack__field_indices_by_name[] = {
  1,   /* field[1] = base_resource */
  2,   /* field[2] = base_time */
  4,   /* field[4] = network_id */
  3,   /* field[3] = network_type */
  0,   /* field[0] = records */
};
static const ProtobufCIntRange telemetry__telemetry_pack__number_ranges[3 + 1] =
{
  { 1, 0 },
  { 4, 2 },
  { 6, 3 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor telemetry__telemetry_pack__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "telemetry.TelemetryPack",
  "TelemetryPack",
  "Telemetry__TelemetryPack",
  "telemetry",
  sizeof(Telemetry__TelemetryPack),
  5,
  telemetry__telemetry_pack__field_descriptors,
  telemetry__telemetry_pack__field_indices_by_name,
  3,  telemetry__telemetry_pack__number_ranges,
  (ProtobufCMessageInit) telemetry__telemetry_pack__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue telemetry__resource__enum_values_by_number[69] =
{
  { "RESOURCE_UNSPECIFIED", "TELEMETRY__RESOURCE__RESOURCE_UNSPECIFIED", 0 },
  { "RESOURCE_TEMPERATURE", "TELEMETRY__RESOURCE__RESOURCE_TEMPERATURE", 1 },
  { "RESOURCE_HUMIDITY", "TELEMETRY__RESOURCE__RESOURCE_HUMIDITY", 2 },
  { "RESOURCE_LATITUDE", "TELEMETRY__RESOURCE__RESOURCE_LATITUDE", 3 },
  { "RESOURCE_LONGITUDE", "TELEMETRY__RESOURCE__RESOURCE_LONGITUDE", 4 },
  { "RESOURCE_ALTITUDE", "TELEMETRY__RESOURCE__RESOURCE_ALTITUDE", 5 },
  { "RESOURCE_POWER", "TELEMETRY__RESOURCE__RESOURCE_POWER", 6 },
  { "RESOURCE_PRESSURE", "TELEMETRY__RESOURCE__RESOURCE_PRESSURE", 7 },
  { "RESOURCE_ANGLE", "TELEMETRY__RESOURCE__RESOURCE_ANGLE", 8 },
  { "RESOURCE_LENGTH", "TELEMETRY__RESOURCE__RESOURCE_LENGTH", 9 },
  { "RESOURCE_BREADTH", "TELEMETRY__RESOURCE__RESOURCE_BREADTH", 10 },
  { "RESOURCE_HEIGHT", "TELEMETRY__RESOURCE__RESOURCE_HEIGHT", 11 },
  { "RESOURCE_WEIGHT", "TELEMETRY__RESOURCE__RESOURCE_WEIGHT", 12 },
  { "RESOURCE_THICKNESS", "TELEMETRY__RESOURCE__RESOURCE_THICKNESS", 13 },
  { "RESOURCE_DISTANCE", "TELEMETRY__RESOURCE__RESOURCE_DISTANCE", 14 },
  { "RESOURCE_AREA", "TELEMETRY__RESOURCE__RESOURCE_AREA", 15 },
  { "RESOURCE_VOLUME", "TELEMETRY__RESOURCE__RESOURCE_VOLUME", 16 },
  { "RESOURCE_VELOCITY", "TELEMETRY__RESOURCE__RESOURCE_VELOCITY", 17 },
  { "RESOURCE_ELECTRIC_CURRENT", "TELEMETRY__RESOURCE__RESOURCE_ELECTRIC_CURRENT", 18 },
  { "RESOURCE_ELECTRIC_POTENTIAL", "TELEMETRY__RESOURCE__RESOURCE_ELECTRIC_POTENTIAL", 19 },
  { "RESOURCE_ELECTRIC_RESISTANCE", "TELEMETRY__RESOURCE__RESOURCE_ELECTRIC_RESISTANCE", 20 },
  { "RESOURCE_ILLUMINANCE", "TELEMETRY__RESOURCE__RESOURCE_ILLUMINANCE", 21 },
  { "RESOURCE_ACCELERATION_X", "TELEMETRY__RESOURCE__RESOURCE_ACCELERATION_X", 22 },
  { "RESOURCE_ACCELERATION_Y", "TELEMETRY__RESOURCE__RESOURCE_ACCELERATION_Y", 23 },
  { "RESOURCE_ACCELERATION_Z", "TELEMETRY__RESOURCE__RESOURCE_ACCELERATION_Z", 24 },
  { "RESOURCE_HEADING", "TELEMETRY__RESOURCE__RESOURCE_HEADING", 25 },
  { "RESOURCE_CO_CONCENTRATION", "TELEMETRY__RESOURCE__RESOURCE_CO_CONCENTRATION", 26 },
  { "RESOURCE_CO2_CONCENTRATION", "TELEMETRY__RESOURCE__RESOURCE_CO2_CONCENTRATION", 27 },
  { "RESOURCE_SOUND", "TELEMETRY__RESOURCE__RESOURCE_SOUND", 28 },
  { "RESOURCE_FREQUENCY", "TELEMETRY__RESOURCE__RESOURCE_FREQUENCY", 29 },
  { "RESOURCE_BATTERY_LEVEL", "TELEMETRY__RESOURCE__RESOURCE_BATTERY_LEVEL", 30 },
  { "RESOURCE_BATTERY_VOLTAGE", "TELEMETRY__RESOURCE__RESOURCE_BATTERY_VOLTAGE", 31 },
  { "RESOURCE_RADIUS", "TELEMETRY__RESOURCE__RESOURCE_RADIUS", 32 },
  { "RESOURCE_BATTERY_LEVEL_LOW", "TELEMETRY__RESOURCE__RESOURCE_BATTERY_LEVEL_LOW", 33 },
  { "RESOURCE_COMPASS_X", "TELEMETRY__RESOURCE__RESOURCE_COMPASS_X", 34 },
  { "RESOURCE_COMPASS_Y", "TELEMETRY__RESOURCE__RESOURCE_COMPASS_Y", 35 },
  { "RESOURCE_COMPASS_Z", "TELEMETRY__RESOURCE__RESOURCE_COMPASS_Z", 36 },
  { "RESOURCE_READ_SWITCH", "TELEMETRY__RESOURCE__RESOURCE_READ_SWITCH", 37 },
  { "RESOURCE_PRESENCE", "TELEMETRY__RESOURCE__RESOURCE_PRESENCE", 38 },
  { "RESOURCE_COUNTER", "TELEMETRY__RESOURCE__RESOURCE_COUNTER", 39 },
  { "RESOURCE_INTERNAL_TEMPERATURE", "TELEMETRY__RESOURCE__RESOURCE_INTERNAL_TEMPERATURE", 40 },
  { "RESOURCE_MOISTURE", "TELEMETRY__RESOURCE__RESOURCE_MOISTURE", 41 },
  { "RESOURCE_APPARENT_POWER", "TELEMETRY__RESOURCE__RESOURCE_APPARENT_POWER", 42 },
  { "RESOURCE_ACCUMULATED_POWER", "TELEMETRY__RESOURCE__RESOURCE_ACCUMULATED_POWER", 43 },
  { "RESOURCE_REACTIVE_POWER", "TELEMETRY__RESOURCE__RESOURCE_REACTIVE_POWER", 44 },
  { "RESOURCE_POWER_FACTOR", "TELEMETRY__RESOURCE__RESOURCE_POWER_FACTOR", 45 },
  { "RESOURCE_LOG", "TELEMETRY__RESOURCE__RESOURCE_LOG", 46 },
  { "RESOURCE_FREE_HEAP_SIZE", "TELEMETRY__RESOURCE__RESOURCE_FREE_HEAP_SIZE", 47 },
  { "RESOURCE_LUMINOUS_FLUX", "TELEMETRY__RESOURCE__RESOURCE_LUMINOUS_FLUX", 48 },
  { "RESOURCE_LUMINOUS_INTENSITY", "TELEMETRY__RESOURCE__RESOURCE_LUMINOUS_INTENSITY", 49 },
  { "RESOURCE_BRIGHTNESS", "TELEMETRY__RESOURCE__RESOURCE_BRIGHTNESS", 50 },
  { "RESOURCE_SWITCH", "TELEMETRY__RESOURCE__RESOURCE_SWITCH", 51 },
  { "RESOURCE_CONFIG", "TELEMETRY__RESOURCE__RESOURCE_CONFIG", 52 },
  { "RESOURCE_IRRADIANCE", "TELEMETRY__RESOURCE__RESOURCE_IRRADIANCE", 53 },
  { "RESOURCE_FIRMWARE_VERSION", "TELEMETRY__RESOURCE__RESOURCE_FIRMWARE_VERSION", 54 },
  { "RESOURCE_HARDWARE_VERSION", "TELEMETRY__RESOURCE__RESOURCE_HARDWARE_VERSION", 55 },
  { "RESOURCE_HARDWARE_ID", "TELEMETRY__RESOURCE__RESOURCE_HARDWARE_ID", 56 },
  { "RESOURCE_MANUFACTURING_DATE", "TELEMETRY__RESOURCE__RESOURCE_MANUFACTURING_DATE", 57 },
  { "RESOURCE_DEVICE_NAME", "TELEMETRY__RESOURCE__RESOURCE_DEVICE_NAME", 58 },
  { "RESOURCE_CONNECTED_NETWORK", "TELEMETRY__RESOURCE__RESOURCE_CONNECTED_NETWORK", 59 },
  { "RESOURCE_CONNECTED", "TELEMETRY__RESOURCE__RESOURCE_CONNECTED", 60 },
  { "RESOURCE_N_CONCENTRATION", "TELEMETRY__RESOURCE__RESOURCE_N_CONCENTRATION", 61 },
  { "RESOURCE_P_CONCENTRATION", "TELEMETRY__RESOURCE__RESOURCE_P_CONCENTRATION", 62 },
  { "RESOURCE_K_CONCENTRATION", "TELEMETRY__RESOURCE__RESOURCE_K_CONCENTRATION", 63 },
  { "RESOURCE_CONDUCTIVITY", "TELEMETRY__RESOURCE__RESOURCE_CONDUCTIVITY", 64 },
  { "RESOURCE_PH", "TELEMETRY__RESOURCE__RESOURCE_PH", 65 },
  { "RESOURCE_MESH_LEVEL", "TELEMETRY__RESOURCE__RESOURCE_MESH_LEVEL", 66 },
  { "RESOURCE_PRECIPITATION", "TELEMETRY__RESOURCE__RESOURCE_PRECIPITATION", 67 },
  { "RESOURCE_SIGNAL_STRENGTH", "TELEMETRY__RESOURCE__RESOURCE_SIGNAL_STRENGTH", 68 },
};
static const ProtobufCIntRange telemetry__resource__value_ranges[] = {
{0, 0},{0, 69}
};
static const ProtobufCEnumValueIndex telemetry__resource__enum_values_by_name[70] =
{
  { "RESOURCE_ACCELERATION_X", 22 },
  { "RESOURCE_ACCELERATION_Y", 23 },
  { "RESOURCE_ACCELERATION_Z", 24 },
  { "RESOURCE_ACCUMULATED_POWER", 43 },
  { "RESOURCE_ALTITUDE", 5 },
  { "RESOURCE_ANGLE", 8 },
  { "RESOURCE_APPARENT_POWER", 42 },
  { "RESOURCE_AREA", 15 },
  { "RESOURCE_BATTERY_LEVEL", 30 },
  { "RESOURCE_BATTERY_LEVEL_LOW", 33 },
  { "RESOURCE_BATTERY_VOLTAGE", 31 },
  { "RESOURCE_BREADTH", 10 },
  { "RESOURCE_BRIGHTENING", 50 },
  { "RESOURCE_BRIGHTNESS", 50 },
  { "RESOURCE_CO2_CONCENTRATION", 27 },
  { "RESOURCE_COMPASS_X", 34 },
  { "RESOURCE_COMPASS_Y", 35 },
  { "RESOURCE_COMPASS_Z", 36 },
  { "RESOURCE_CONDUCTIVITY", 64 },
  { "RESOURCE_CONFIG", 52 },
  { "RESOURCE_CONNECTED", 60 },
  { "RESOURCE_CONNECTED_NETWORK", 59 },
  { "RESOURCE_COUNTER", 39 },
  { "RESOURCE_CO_CONCENTRATION", 26 },
  { "RESOURCE_DEVICE_NAME", 58 },
  { "RESOURCE_DISTANCE", 14 },
  { "RESOURCE_ELECTRIC_CURRENT", 18 },
  { "RESOURCE_ELECTRIC_POTENTIAL", 19 },
  { "RESOURCE_ELECTRIC_RESISTANCE", 20 },
  { "RESOURCE_FIRMWARE_VERSION", 54 },
  { "RESOURCE_FREE_HEAP_SIZE", 47 },
  { "RESOURCE_FREQUENCY", 29 },
  { "RESOURCE_HARDWARE_ID", 56 },
  { "RESOURCE_HARDWARE_VERSION", 55 },
  { "RESOURCE_HEADING", 25 },
  { "RESOURCE_HEIGHT", 11 },
  { "RESOURCE_HUMIDITY", 2 },
  { "RESOURCE_ILLUMINANCE", 21 },
  { "RESOURCE_INTERNAL_TEMPERATURE", 40 },
  { "RESOURCE_IRRADIANCE", 53 },
  { "RESOURCE_K_CONCENTRATION", 63 },
  { "RESOURCE_LATITUDE", 3 },
  { "RESOURCE_LENGTH", 9 },
  { "RESOURCE_LOG", 46 },
  { "RESOURCE_LONGITUDE", 4 },
  { "RESOURCE_LUMINOUS_FLUX", 48 },
  { "RESOURCE_LUMINOUS_INTENSITY", 49 },
  { "RESOURCE_MANUFACTURING_DATE", 57 },
  { "RESOURCE_MESH_LEVEL", 66 },
  { "RESOURCE_MOISTURE", 41 },
  { "RESOURCE_N_CONCENTRATION", 61 },
  { "RESOURCE_PH", 65 },
  { "RESOURCE_POWER", 6 },
  { "RESOURCE_POWER_FACTOR", 45 },
  { "RESOURCE_PRECIPITATION", 67 },
  { "RESOURCE_PRESENCE", 38 },
  { "RESOURCE_PRESSURE", 7 },
  { "RESOURCE_P_CONCENTRATION", 62 },
  { "RESOURCE_RADIUS", 32 },
  { "RESOURCE_REACTIVE_POWER", 44 },
  { "RESOURCE_READ_SWITCH", 37 },
  { "RESOURCE_SIGNAL_STRENGTH", 68 },
  { "RESOURCE_SOUND", 28 },
  { "RESOURCE_SWITCH", 51 },
  { "RESOURCE_TEMPERATURE", 1 },
  { "RESOURCE_THICKNESS", 13 },
  { "RESOURCE_UNSPECIFIED", 0 },
  { "RESOURCE_VELOCITY", 17 },
  { "RESOURCE_VOLUME", 16 },
  { "RESOURCE_WEIGHT", 12 },
};
const ProtobufCEnumDescriptor telemetry__resource__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "telemetry.Resource",
  "Resource",
  "Telemetry__Resource",
  "telemetry",
  69,
  telemetry__resource__enum_values_by_number,
  70,
  telemetry__resource__enum_values_by_name,
  1,
  telemetry__resource__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue telemetry__network_type__enum_values_by_number[5] =
{
  { "NETWORK_TYPE_UNSPECIFIED", "TELEMETRY__NETWORK_TYPE__NETWORK_TYPE_UNSPECIFIED", 0 },
  { "NETWORK_TYPE_MQTT_1", "TELEMETRY__NETWORK_TYPE__NETWORK_TYPE_MQTT_1", 1 },
  { "NETWORK_TYPE_LORAWAN_1", "TELEMETRY__NETWORK_TYPE__NETWORK_TYPE_LORAWAN_1", 2 },
  { "NETWORK_TYPE_LORAWAN_2", "TELEMETRY__NETWORK_TYPE__NETWORK_TYPE_LORAWAN_2", 3 },
  { "NETWORK_TYPE_LORAWAN_3", "TELEMETRY__NETWORK_TYPE__NETWORK_TYPE_LORAWAN_3", 4 },
};
static const ProtobufCIntRange telemetry__network_type__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex telemetry__network_type__enum_values_by_name[5] =
{
  { "NETWORK_TYPE_LORAWAN_1", 2 },
  { "NETWORK_TYPE_LORAWAN_2", 3 },
  { "NETWORK_TYPE_LORAWAN_3", 4 },
  { "NETWORK_TYPE_MQTT_1", 1 },
  { "NETWORK_TYPE_UNSPECIFIED", 0 },
};
const ProtobufCEnumDescriptor telemetry__network_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "telemetry.NetworkType",
  "NetworkType",
  "Telemetry__NetworkType",
  "telemetry",
  5,
  telemetry__network_type__enum_values_by_number,
  5,
  telemetry__network_type__enum_values_by_name,
  1,
  telemetry__network_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue telemetry__severity__enum_values_by_number[4] =
{
  { "SEVERITY_UNSPECIFIED", "TELEMETRY__SEVERITY__SEVERITY_UNSPECIFIED", 0 },
  { "SEVERITY_LOW", "TELEMETRY__SEVERITY__SEVERITY_LOW", 1 },
  { "SEVERITY_HIGH", "TELEMETRY__SEVERITY__SEVERITY_HIGH", 2 },
  { "SEVERITY_URGENT", "TELEMETRY__SEVERITY__SEVERITY_URGENT", 3 },
};
static const ProtobufCIntRange telemetry__severity__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex telemetry__severity__enum_values_by_name[4] =
{
  { "SEVERITY_HIGH", 2 },
  { "SEVERITY_LOW", 1 },
  { "SEVERITY_UNSPECIFIED", 0 },
  { "SEVERITY_URGENT", 3 },
};
const ProtobufCEnumDescriptor telemetry__severity__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "telemetry.Severity",
  "Severity",
  "Telemetry__Severity",
  "telemetry",
  4,
  telemetry__severity__enum_values_by_number,
  4,
  telemetry__severity__enum_values_by_name,
  1,
  telemetry__severity__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
