/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: telemetry/telemetry.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "telemetry/telemetry.pb-c.h"
void   telemetry__sem_ver__init
                     (Telemetry__SemVer         *message)
{
  static const Telemetry__SemVer init_value = TELEMETRY__SEM_VER__INIT;
  *message = init_value;
}
size_t telemetry__sem_ver__get_packed_size
                     (const Telemetry__SemVer *message)
{
  assert(message->base.descriptor == &telemetry__sem_ver__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t telemetry__sem_ver__pack
                     (const Telemetry__SemVer *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &telemetry__sem_ver__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t telemetry__sem_ver__pack_to_buffer
                     (const Telemetry__SemVer *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &telemetry__sem_ver__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Telemetry__SemVer *
       telemetry__sem_ver__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Telemetry__SemVer *)
     protobuf_c_message_unpack (&telemetry__sem_ver__descriptor,
                                allocator, len, data);
}
void   telemetry__sem_ver__free_unpacked
                     (Telemetry__SemVer *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &telemetry__sem_ver__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   telemetry__record__init
                     (Telemetry__Record         *message)
{
  static const Telemetry__Record init_value = TELEMETRY__RECORD__INIT;
  *message = init_value;
}
size_t telemetry__record__get_packed_size
                     (const Telemetry__Record *message)
{
  assert(message->base.descriptor == &telemetry__record__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t telemetry__record__pack
                     (const Telemetry__Record *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &telemetry__record__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t telemetry__record__pack_to_buffer
                     (const Telemetry__Record *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &telemetry__record__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Telemetry__Record *
       telemetry__record__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Telemetry__Record *)
     protobuf_c_message_unpack (&telemetry__record__descriptor,
                                allocator, len, data);
}
void   telemetry__record__free_unpacked
                     (Telemetry__Record *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &telemetry__record__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   telemetry__telemetry_pack__init
                     (Telemetry__TelemetryPack         *message)
{
  static const Telemetry__TelemetryPack init_value = TELEMETRY__TELEMETRY_PACK__INIT;
  *message = init_value;
}
size_t telemetry__telemetry_pack__get_packed_size
                     (const Telemetry__TelemetryPack *message)
{
  assert(message->base.descriptor == &telemetry__telemetry_pack__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t telemetry__telemetry_pack__pack
                     (const Telemetry__TelemetryPack *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &telemetry__telemetry_pack__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t telemetry__telemetry_pack__pack_to_buffer
                     (const Telemetry__TelemetryPack *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &telemetry__telemetry_pack__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Telemetry__TelemetryPack *
       telemetry__telemetry_pack__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Telemetry__TelemetryPack *)
     protobuf_c_message_unpack (&telemetry__telemetry_pack__descriptor,
                                allocator, len, data);
}
void   telemetry__telemetry_pack__free_unpacked
                     (Telemetry__TelemetryPack *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &telemetry__telemetry_pack__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor telemetry__sem_ver__field_descriptors[3] =
{
  {
    "major",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Telemetry__SemVer, major),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "minor",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Telemetry__SemVer, minor),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "patch",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Telemetry__SemVer, patch),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned telemetry__sem_ver__field_indices_by_name[] = {
  0,   /* field[0] = major */
  1,   /* field[1] = minor */
  2,   /* field[2] = patch */
};
static const ProtobufCIntRange telemetry__sem_ver__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor telemetry__sem_ver__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "telemetry.SemVer",
  "SemVer",
  "Telemetry__SemVer",
  "telemetry",
  sizeof(Telemetry__SemVer),
  3,
  telemetry__sem_ver__field_descriptors,
  telemetry__sem_ver__field_indices_by_name,
  1,  telemetry__sem_ver__number_ranges,
  (ProtobufCMessageInit) telemetry__sem_ver__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor telemetry__record__field_descriptors[11] =
{
  {
    "resource",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Telemetry__Record, resource),
    &telemetry__resource__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Telemetry__Record, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "unit",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Telemetry__Record, unit),
    &telemetry__unit__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "time",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Telemetry__Record, time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Telemetry__Record, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "string_value",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Telemetry__Record, string_value),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bool_value",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Telemetry__Record, bool_value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data_value",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Telemetry__Record, data_value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "severity",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Telemetry__Record, severity),
    &telemetry__severity__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "alert_id",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Telemetry__Record, alert_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "int_value",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Telemetry__Record, int_value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned telemetry__record__field_indices_by_name[] = {
  9,   /* field[9] = alert_id */
  6,   /* field[6] = bool_value */
  7,   /* field[7] = data_value */
  10,   /* field[10] = int_value */
  1,   /* field[1] = name */
  0,   /* field[0] = resource */
  8,   /* field[8] = severity */
  5,   /* field[5] = string_value */
  3,   /* field[3] = time */
  2,   /* field[2] = unit */
  4,   /* field[4] = value */
};
static const ProtobufCIntRange telemetry__record__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor telemetry__record__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "telemetry.Record",
  "Record",
  "Telemetry__Record",
  "telemetry",
  sizeof(Telemetry__Record),
  11,
  telemetry__record__field_descriptors,
  telemetry__record__field_indices_by_name,
  1,  telemetry__record__number_ranges,
  (ProtobufCMessageInit) telemetry__record__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor telemetry__telemetry_pack__field_descriptors[7] =
{
  {
    "records",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Telemetry__TelemetryPack, n_records),
    offsetof(Telemetry__TelemetryPack, records),
    &telemetry__record__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "base_resource",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Telemetry__TelemetryPack, base_resource),
    &telemetry__resource__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "base_name",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Telemetry__TelemetryPack, base_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "base_time",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Telemetry__TelemetryPack, base_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "base_unit",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Telemetry__TelemetryPack, base_unit),
    &telemetry__unit__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "network_type",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Telemetry__TelemetryPack, network_type),
    &telemetry__network_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "network_id",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Telemetry__TelemetryPack, network_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned telemetry__telemetry_pack__field_indices_by_name[] = {
  2,   /* field[2] = base_name */
  1,   /* field[1] = base_resource */
  3,   /* field[3] = base_time */
  4,   /* field[4] = base_unit */
  6,   /* field[6] = network_id */
  5,   /* field[5] = network_type */
  0,   /* field[0] = records */
};
static const ProtobufCIntRange telemetry__telemetry_pack__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor telemetry__telemetry_pack__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "telemetry.TelemetryPack",
  "TelemetryPack",
  "Telemetry__TelemetryPack",
  "telemetry",
  sizeof(Telemetry__TelemetryPack),
  7,
  telemetry__telemetry_pack__field_descriptors,
  telemetry__telemetry_pack__field_indices_by_name,
  1,  telemetry__telemetry_pack__number_ranges,
  (ProtobufCMessageInit) telemetry__telemetry_pack__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue telemetry__resource__enum_values_by_number[66] =
{
  { "RESOURCE_UNSPECIFIED", "TELEMETRY__RESOURCE__RESOURCE_UNSPECIFIED", 0 },
  { "RESOURCE_TEMPERATURE", "TELEMETRY__RESOURCE__RESOURCE_TEMPERATURE", 1 },
  { "RESOURCE_HUMIDITY", "TELEMETRY__RESOURCE__RESOURCE_HUMIDITY", 2 },
  { "RESOURCE_LATITUDE", "TELEMETRY__RESOURCE__RESOURCE_LATITUDE", 3 },
  { "RESOURCE_LONGITUDE", "TELEMETRY__RESOURCE__RESOURCE_LONGITUDE", 4 },
  { "RESOURCE_ALTITUDE", "TELEMETRY__RESOURCE__RESOURCE_ALTITUDE", 5 },
  { "RESOURCE_POWER", "TELEMETRY__RESOURCE__RESOURCE_POWER", 6 },
  { "RESOURCE_PRESSURE", "TELEMETRY__RESOURCE__RESOURCE_PRESSURE", 7 },
  { "RESOURCE_ANGLE", "TELEMETRY__RESOURCE__RESOURCE_ANGLE", 8 },
  { "RESOURCE_LENGTH", "TELEMETRY__RESOURCE__RESOURCE_LENGTH", 9 },
  { "RESOURCE_BREADTH", "TELEMETRY__RESOURCE__RESOURCE_BREADTH", 10 },
  { "RESOURCE_HEIGHT", "TELEMETRY__RESOURCE__RESOURCE_HEIGHT", 11 },
  { "RESOURCE_WEIGHT", "TELEMETRY__RESOURCE__RESOURCE_WEIGHT", 12 },
  { "RESOURCE_THICKNESS", "TELEMETRY__RESOURCE__RESOURCE_THICKNESS", 13 },
  { "RESOURCE_DISTANCE", "TELEMETRY__RESOURCE__RESOURCE_DISTANCE", 14 },
  { "RESOURCE_AREA", "TELEMETRY__RESOURCE__RESOURCE_AREA", 15 },
  { "RESOURCE_VOLUME", "TELEMETRY__RESOURCE__RESOURCE_VOLUME", 16 },
  { "RESOURCE_VELOCITY", "TELEMETRY__RESOURCE__RESOURCE_VELOCITY", 17 },
  { "RESOURCE_ELECTRIC_CURRENT", "TELEMETRY__RESOURCE__RESOURCE_ELECTRIC_CURRENT", 18 },
  { "RESOURCE_ELECTRIC_POTENTIAL", "TELEMETRY__RESOURCE__RESOURCE_ELECTRIC_POTENTIAL", 19 },
  { "RESOURCE_ELECTRIC_RESISTANCE", "TELEMETRY__RESOURCE__RESOURCE_ELECTRIC_RESISTANCE", 20 },
  { "RESOURCE_ILLUMINANCE", "TELEMETRY__RESOURCE__RESOURCE_ILLUMINANCE", 21 },
  { "RESOURCE_ACCELERATION_X", "TELEMETRY__RESOURCE__RESOURCE_ACCELERATION_X", 22 },
  { "RESOURCE_ACCELERATION_Y", "TELEMETRY__RESOURCE__RESOURCE_ACCELERATION_Y", 23 },
  { "RESOURCE_ACCELERATION_Z", "TELEMETRY__RESOURCE__RESOURCE_ACCELERATION_Z", 24 },
  { "RESOURCE_HEADING", "TELEMETRY__RESOURCE__RESOURCE_HEADING", 25 },
  { "RESOURCE_CO_CONCENTRATION", "TELEMETRY__RESOURCE__RESOURCE_CO_CONCENTRATION", 26 },
  { "RESOURCE_CO2_CONCENTRATION", "TELEMETRY__RESOURCE__RESOURCE_CO2_CONCENTRATION", 27 },
  { "RESOURCE_SOUND", "TELEMETRY__RESOURCE__RESOURCE_SOUND", 28 },
  { "RESOURCE_FREQUENCY", "TELEMETRY__RESOURCE__RESOURCE_FREQUENCY", 29 },
  { "RESOURCE_BATTERY_LEVEL", "TELEMETRY__RESOURCE__RESOURCE_BATTERY_LEVEL", 30 },
  { "RESOURCE_BATTERY_VOLTAGE", "TELEMETRY__RESOURCE__RESOURCE_BATTERY_VOLTAGE", 31 },
  { "RESOURCE_RADIUS", "TELEMETRY__RESOURCE__RESOURCE_RADIUS", 32 },
  { "RESOURCE_BATTERY_LEVEL_LOW", "TELEMETRY__RESOURCE__RESOURCE_BATTERY_LEVEL_LOW", 33 },
  { "RESOURCE_COMPASS_X", "TELEMETRY__RESOURCE__RESOURCE_COMPASS_X", 34 },
  { "RESOURCE_COMPASS_Y", "TELEMETRY__RESOURCE__RESOURCE_COMPASS_Y", 35 },
  { "RESOURCE_COMPASS_Z", "TELEMETRY__RESOURCE__RESOURCE_COMPASS_Z", 36 },
  { "RESOURCE_READ_SWITCH", "TELEMETRY__RESOURCE__RESOURCE_READ_SWITCH", 37 },
  { "RESOURCE_PRESENCE", "TELEMETRY__RESOURCE__RESOURCE_PRESENCE", 38 },
  { "RESOURCE_COUNTER", "TELEMETRY__RESOURCE__RESOURCE_COUNTER", 39 },
  { "RESOURCE_INTERNAL_TEMPERATURE", "TELEMETRY__RESOURCE__RESOURCE_INTERNAL_TEMPERATURE", 40 },
  { "RESOURCE_MOISTURE", "TELEMETRY__RESOURCE__RESOURCE_MOISTURE", 41 },
  { "RESOURCE_APPARENT_POWER", "TELEMETRY__RESOURCE__RESOURCE_APPARENT_POWER", 42 },
  { "RESOURCE_ACCUMULATED_POWER", "TELEMETRY__RESOURCE__RESOURCE_ACCUMULATED_POWER", 43 },
  { "RESOURCE_REACTIVE_POWER", "TELEMETRY__RESOURCE__RESOURCE_REACTIVE_POWER", 44 },
  { "RESOURCE_POWER_FACTOR", "TELEMETRY__RESOURCE__RESOURCE_POWER_FACTOR", 45 },
  { "RESOURCE_LOG", "TELEMETRY__RESOURCE__RESOURCE_LOG", 46 },
  { "RESOURCE_FREE_HEAP_SIZE", "TELEMETRY__RESOURCE__RESOURCE_FREE_HEAP_SIZE", 47 },
  { "RESOURCE_LUMINOUS_FLUX", "TELEMETRY__RESOURCE__RESOURCE_LUMINOUS_FLUX", 48 },
  { "RESOURCE_LUMINOUS_INTENSITY", "TELEMETRY__RESOURCE__RESOURCE_LUMINOUS_INTENSITY", 49 },
  { "RESOURCE_BRIGHTESS", "TELEMETRY__RESOURCE__RESOURCE_BRIGHTESS", 50 },
  { "RESOURCE_SWITCH", "TELEMETRY__RESOURCE__RESOURCE_SWITCH", 51 },
  { "RESOURCE_CONFIG", "TELEMETRY__RESOURCE__RESOURCE_CONFIG", 52 },
  { "RESOURCE_IRRADIANCE", "TELEMETRY__RESOURCE__RESOURCE_IRRADIANCE", 53 },
  { "RESOURCE_FIRMWARE_VERSION", "TELEMETRY__RESOURCE__RESOURCE_FIRMWARE_VERSION", 54 },
  { "RESOURCE_HARDWARE_VERSION", "TELEMETRY__RESOURCE__RESOURCE_HARDWARE_VERSION", 55 },
  { "RESOURCE_HARDWARE_ID", "TELEMETRY__RESOURCE__RESOURCE_HARDWARE_ID", 56 },
  { "RESOURCE_MANUFACTURING_DATE", "TELEMETRY__RESOURCE__RESOURCE_MANUFACTURING_DATE", 57 },
  { "RESOURCE_DEVICE_NAME", "TELEMETRY__RESOURCE__RESOURCE_DEVICE_NAME", 58 },
  { "RESOURCE_CONNECTED_NETWORK", "TELEMETRY__RESOURCE__RESOURCE_CONNECTED_NETWORK", 59 },
  { "RESOURCE_CONNECTED", "TELEMETRY__RESOURCE__RESOURCE_CONNECTED", 60 },
  { "RESOURCE_N_CONCENTRATION", "TELEMETRY__RESOURCE__RESOURCE_N_CONCENTRATION", 61 },
  { "RESOURCE_P_CONCENTRATION", "TELEMETRY__RESOURCE__RESOURCE_P_CONCENTRATION", 62 },
  { "RESOURCE_K_CONCENTRATION", "TELEMETRY__RESOURCE__RESOURCE_K_CONCENTRATION", 63 },
  { "RESOURCE_CONDUCTIVITY", "TELEMETRY__RESOURCE__RESOURCE_CONDUCTIVITY", 64 },
  { "RESOURCE_PH", "TELEMETRY__RESOURCE__RESOURCE_PH", 65 },
};
static const ProtobufCIntRange telemetry__resource__value_ranges[] = {
{0, 0},{0, 66}
};
static const ProtobufCEnumValueIndex telemetry__resource__enum_values_by_name[67] =
{
  { "RESOURCE_ACCELERATION_X", 22 },
  { "RESOURCE_ACCELERATION_Y", 23 },
  { "RESOURCE_ACCELERATION_Z", 24 },
  { "RESOURCE_ACCUMULATED_POWER", 43 },
  { "RESOURCE_ALTITUDE", 5 },
  { "RESOURCE_ANGLE", 8 },
  { "RESOURCE_APPARENT_POWER", 42 },
  { "RESOURCE_AREA", 15 },
  { "RESOURCE_BATTERY_LEVEL", 30 },
  { "RESOURCE_BATTERY_LEVEL_LOW", 33 },
  { "RESOURCE_BATTERY_VOLTAGE", 31 },
  { "RESOURCE_BREADTH", 10 },
  { "RESOURCE_BRIGHTENING", 50 },
  { "RESOURCE_BRIGHTESS", 50 },
  { "RESOURCE_CO2_CONCENTRATION", 27 },
  { "RESOURCE_COMPASS_X", 34 },
  { "RESOURCE_COMPASS_Y", 35 },
  { "RESOURCE_COMPASS_Z", 36 },
  { "RESOURCE_CONDUCTIVITY", 64 },
  { "RESOURCE_CONFIG", 52 },
  { "RESOURCE_CONNECTED", 60 },
  { "RESOURCE_CONNECTED_NETWORK", 59 },
  { "RESOURCE_COUNTER", 39 },
  { "RESOURCE_CO_CONCENTRATION", 26 },
  { "RESOURCE_DEVICE_NAME", 58 },
  { "RESOURCE_DISTANCE", 14 },
  { "RESOURCE_ELECTRIC_CURRENT", 18 },
  { "RESOURCE_ELECTRIC_POTENTIAL", 19 },
  { "RESOURCE_ELECTRIC_RESISTANCE", 20 },
  { "RESOURCE_FIRMWARE_VERSION", 54 },
  { "RESOURCE_FREE_HEAP_SIZE", 47 },
  { "RESOURCE_FREQUENCY", 29 },
  { "RESOURCE_HARDWARE_ID", 56 },
  { "RESOURCE_HARDWARE_VERSION", 55 },
  { "RESOURCE_HEADING", 25 },
  { "RESOURCE_HEIGHT", 11 },
  { "RESOURCE_HUMIDITY", 2 },
  { "RESOURCE_ILLUMINANCE", 21 },
  { "RESOURCE_INTERNAL_TEMPERATURE", 40 },
  { "RESOURCE_IRRADIANCE", 53 },
  { "RESOURCE_K_CONCENTRATION", 63 },
  { "RESOURCE_LATITUDE", 3 },
  { "RESOURCE_LENGTH", 9 },
  { "RESOURCE_LOG", 46 },
  { "RESOURCE_LONGITUDE", 4 },
  { "RESOURCE_LUMINOUS_FLUX", 48 },
  { "RESOURCE_LUMINOUS_INTENSITY", 49 },
  { "RESOURCE_MANUFACTURING_DATE", 57 },
  { "RESOURCE_MOISTURE", 41 },
  { "RESOURCE_N_CONCENTRATION", 61 },
  { "RESOURCE_PH", 65 },
  { "RESOURCE_POWER", 6 },
  { "RESOURCE_POWER_FACTOR", 45 },
  { "RESOURCE_PRESENCE", 38 },
  { "RESOURCE_PRESSURE", 7 },
  { "RESOURCE_P_CONCENTRATION", 62 },
  { "RESOURCE_RADIUS", 32 },
  { "RESOURCE_REACTIVE_POWER", 44 },
  { "RESOURCE_READ_SWITCH", 37 },
  { "RESOURCE_SOUND", 28 },
  { "RESOURCE_SWITCH", 51 },
  { "RESOURCE_TEMPERATURE", 1 },
  { "RESOURCE_THICKNESS", 13 },
  { "RESOURCE_UNSPECIFIED", 0 },
  { "RESOURCE_VELOCITY", 17 },
  { "RESOURCE_VOLUME", 16 },
  { "RESOURCE_WEIGHT", 12 },
};
const ProtobufCEnumDescriptor telemetry__resource__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "telemetry.Resource",
  "Resource",
  "Telemetry__Resource",
  "telemetry",
  66,
  telemetry__resource__enum_values_by_number,
  67,
  telemetry__resource__enum_values_by_name,
  1,
  telemetry__resource__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue telemetry__unit__enum_values_by_number[62] =
{
  { "UNIT_UNSPECIFIED", "TELEMETRY__UNIT__UNIT_UNSPECIFIED", 0 },
  { "UNIT_METER", "TELEMETRY__UNIT__UNIT_METER", 1 },
  { "UNIT_KILOGRAM", "TELEMETRY__UNIT__UNIT_KILOGRAM", 2 },
  { "UNIT_GRAM", "TELEMETRY__UNIT__UNIT_GRAM", 3 },
  { "UNIT_SECOND", "TELEMETRY__UNIT__UNIT_SECOND", 4 },
  { "UNIT_AMPERE", "TELEMETRY__UNIT__UNIT_AMPERE", 5 },
  { "UNIT_KELVIN", "TELEMETRY__UNIT__UNIT_KELVIN", 6 },
  { "UNIT_CANDELA", "TELEMETRY__UNIT__UNIT_CANDELA", 7 },
  { "UNIT_MOLE", "TELEMETRY__UNIT__UNIT_MOLE", 8 },
  { "UNIT_HERTZ", "TELEMETRY__UNIT__UNIT_HERTZ", 9 },
  { "UNIT_RADIAN", "TELEMETRY__UNIT__UNIT_RADIAN", 10 },
  { "UNIT_STERADIAN", "TELEMETRY__UNIT__UNIT_STERADIAN", 11 },
  { "UNIT_NEWTON", "TELEMETRY__UNIT__UNIT_NEWTON", 12 },
  { "UNIT_PASCAL", "TELEMETRY__UNIT__UNIT_PASCAL", 13 },
  { "UNIT_JOULE", "TELEMETRY__UNIT__UNIT_JOULE", 14 },
  { "UNIT_WATT", "TELEMETRY__UNIT__UNIT_WATT", 15 },
  { "UNIT_COULOMB", "TELEMETRY__UNIT__UNIT_COULOMB", 16 },
  { "UNIT_VOLT", "TELEMETRY__UNIT__UNIT_VOLT", 17 },
  { "UNIT_FARAD", "TELEMETRY__UNIT__UNIT_FARAD", 18 },
  { "UNIT_OHM", "TELEMETRY__UNIT__UNIT_OHM", 19 },
  { "UNIT_SIEMENS", "TELEMETRY__UNIT__UNIT_SIEMENS", 20 },
  { "UNIT_WEBER", "TELEMETRY__UNIT__UNIT_WEBER", 21 },
  { "UNIT_TESLA", "TELEMETRY__UNIT__UNIT_TESLA", 22 },
  { "UNIT_HENRY", "TELEMETRY__UNIT__UNIT_HENRY", 23 },
  { "UNIT_DEGREES_CELSIUS", "TELEMETRY__UNIT__UNIT_DEGREES_CELSIUS", 24 },
  { "UNIT_LUMEN", "TELEMETRY__UNIT__UNIT_LUMEN", 25 },
  { "UNIT_LUX", "TELEMETRY__UNIT__UNIT_LUX", 26 },
  { "UNIT_BECQUEREL", "TELEMETRY__UNIT__UNIT_BECQUEREL", 27 },
  { "UNIT_GRAY", "TELEMETRY__UNIT__UNIT_GRAY", 28 },
  { "UNIT_SIEVERT", "TELEMETRY__UNIT__UNIT_SIEVERT", 29 },
  { "UNIT_KATAL", "TELEMETRY__UNIT__UNIT_KATAL", 30 },
  { "UNIT_SQUARE_METER", "TELEMETRY__UNIT__UNIT_SQUARE_METER", 31 },
  { "UNIT_CUBIC_METER", "TELEMETRY__UNIT__UNIT_CUBIC_METER", 32 },
  { "UNIT_LITER", "TELEMETRY__UNIT__UNIT_LITER", 33 },
  { "UNIT_METER_PER_SECOND", "TELEMETRY__UNIT__UNIT_METER_PER_SECOND", 34 },
  { "UNIT_METER_PER_SQUARE_SECOND", "TELEMETRY__UNIT__UNIT_METER_PER_SQUARE_SECOND", 35 },
  { "UNIT_CUBIC_METER_PER_SECOND", "TELEMETRY__UNIT__UNIT_CUBIC_METER_PER_SECOND", 36 },
  { "UNIT_LITER_PER_SECOND", "TELEMETRY__UNIT__UNIT_LITER_PER_SECOND", 37 },
  { "UNIT_WATT_PER_SQUARE_METER", "TELEMETRY__UNIT__UNIT_WATT_PER_SQUARE_METER", 38 },
  { "UNIT_CANDELA_PER_SQUARE_METER", "TELEMETRY__UNIT__UNIT_CANDELA_PER_SQUARE_METER", 39 },
  { "UNIT_BIT", "TELEMETRY__UNIT__UNIT_BIT", 40 },
  { "UNIT_BIT_PER_SECOND", "TELEMETRY__UNIT__UNIT_BIT_PER_SECOND", 41 },
  { "UNIT_BYTE", "TELEMETRY__UNIT__UNIT_BYTE", 42 },
  { "UNIT_BYTE_PER_SECOND", "TELEMETRY__UNIT__UNIT_BYTE_PER_SECOND", 43 },
  { "UNIT_LATITUDE", "TELEMETRY__UNIT__UNIT_LATITUDE", 44 },
  { "UNIT_LONGITUDE", "TELEMETRY__UNIT__UNIT_LONGITUDE", 45 },
  { "UNIT_PH", "TELEMETRY__UNIT__UNIT_PH", 46 },
  { "UNIT_DECIBEL", "TELEMETRY__UNIT__UNIT_DECIBEL", 47 },
  { "UNIT_DECIBEL_WATT", "TELEMETRY__UNIT__UNIT_DECIBEL_WATT", 48 },
  { "UNIT_BEL", "TELEMETRY__UNIT__UNIT_BEL", 49 },
  { "UNIT_COUNT", "TELEMETRY__UNIT__UNIT_COUNT", 50 },
  { "UNIT_RATIO", "TELEMETRY__UNIT__UNIT_RATIO", 51 },
  { "UNIT_RELATIVE_HUMIDITY_PERCENTAGE", "TELEMETRY__UNIT__UNIT_RELATIVE_HUMIDITY_PERCENTAGE", 52 },
  { "UNIT_ENERGY_LEVEL_PERCENTAGE", "TELEMETRY__UNIT__UNIT_ENERGY_LEVEL_PERCENTAGE", 53 },
  { "UNIT_ENERGY_LEVEL_SECONDS_REMAINING", "TELEMETRY__UNIT__UNIT_ENERGY_LEVEL_SECONDS_REMAINING", 54 },
  { "UNIT_RATE_PER_SECOND", "TELEMETRY__UNIT__UNIT_RATE_PER_SECOND", 55 },
  { "UNIT_RATE_PER_MINUTE", "TELEMETRY__UNIT__UNIT_RATE_PER_MINUTE", 56 },
  { "UNIT_BEAT_PER_MINUTE", "TELEMETRY__UNIT__UNIT_BEAT_PER_MINUTE", 57 },
  { "UNIT_BEAT", "TELEMETRY__UNIT__UNIT_BEAT", 58 },
  { "UNIT_SIEMENS_PER_METER", "TELEMETRY__UNIT__UNIT_SIEMENS_PER_METER", 59 },
  { "UNIT_PART_PER_MILLION", "TELEMETRY__UNIT__UNIT_PART_PER_MILLION", 60 },
  { "UNIT_VOLT_AMPERE", "TELEMETRY__UNIT__UNIT_VOLT_AMPERE", 61 },
};
static const ProtobufCIntRange telemetry__unit__value_ranges[] = {
{0, 0},{0, 62}
};
static const ProtobufCEnumValueIndex telemetry__unit__enum_values_by_name[62] =
{
  { "UNIT_AMPERE", 5 },
  { "UNIT_BEAT", 58 },
  { "UNIT_BEAT_PER_MINUTE", 57 },
  { "UNIT_BECQUEREL", 27 },
  { "UNIT_BEL", 49 },
  { "UNIT_BIT", 40 },
  { "UNIT_BIT_PER_SECOND", 41 },
  { "UNIT_BYTE", 42 },
  { "UNIT_BYTE_PER_SECOND", 43 },
  { "UNIT_CANDELA", 7 },
  { "UNIT_CANDELA_PER_SQUARE_METER", 39 },
  { "UNIT_COULOMB", 16 },
  { "UNIT_COUNT", 50 },
  { "UNIT_CUBIC_METER", 32 },
  { "UNIT_CUBIC_METER_PER_SECOND", 36 },
  { "UNIT_DECIBEL", 47 },
  { "UNIT_DECIBEL_WATT", 48 },
  { "UNIT_DEGREES_CELSIUS", 24 },
  { "UNIT_ENERGY_LEVEL_PERCENTAGE", 53 },
  { "UNIT_ENERGY_LEVEL_SECONDS_REMAINING", 54 },
  { "UNIT_FARAD", 18 },
  { "UNIT_GRAM", 3 },
  { "UNIT_GRAY", 28 },
  { "UNIT_HENRY", 23 },
  { "UNIT_HERTZ", 9 },
  { "UNIT_JOULE", 14 },
  { "UNIT_KATAL", 30 },
  { "UNIT_KELVIN", 6 },
  { "UNIT_KILOGRAM", 2 },
  { "UNIT_LATITUDE", 44 },
  { "UNIT_LITER", 33 },
  { "UNIT_LITER_PER_SECOND", 37 },
  { "UNIT_LONGITUDE", 45 },
  { "UNIT_LUMEN", 25 },
  { "UNIT_LUX", 26 },
  { "UNIT_METER", 1 },
  { "UNIT_METER_PER_SECOND", 34 },
  { "UNIT_METER_PER_SQUARE_SECOND", 35 },
  { "UNIT_MOLE", 8 },
  { "UNIT_NEWTON", 12 },
  { "UNIT_OHM", 19 },
  { "UNIT_PART_PER_MILLION", 60 },
  { "UNIT_PASCAL", 13 },
  { "UNIT_PH", 46 },
  { "UNIT_RADIAN", 10 },
  { "UNIT_RATE_PER_MINUTE", 56 },
  { "UNIT_RATE_PER_SECOND", 55 },
  { "UNIT_RATIO", 51 },
  { "UNIT_RELATIVE_HUMIDITY_PERCENTAGE", 52 },
  { "UNIT_SECOND", 4 },
  { "UNIT_SIEMENS", 20 },
  { "UNIT_SIEMENS_PER_METER", 59 },
  { "UNIT_SIEVERT", 29 },
  { "UNIT_SQUARE_METER", 31 },
  { "UNIT_STERADIAN", 11 },
  { "UNIT_TESLA", 22 },
  { "UNIT_UNSPECIFIED", 0 },
  { "UNIT_VOLT", 17 },
  { "UNIT_VOLT_AMPERE", 61 },
  { "UNIT_WATT", 15 },
  { "UNIT_WATT_PER_SQUARE_METER", 38 },
  { "UNIT_WEBER", 21 },
};
const ProtobufCEnumDescriptor telemetry__unit__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "telemetry.Unit",
  "Unit",
  "Telemetry__Unit",
  "telemetry",
  62,
  telemetry__unit__enum_values_by_number,
  62,
  telemetry__unit__enum_values_by_name,
  1,
  telemetry__unit__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue telemetry__network_type__enum_values_by_number[5] =
{
  { "NETWORK_TYPE_UNSPECIFIED", "TELEMETRY__NETWORK_TYPE__NETWORK_TYPE_UNSPECIFIED", 0 },
  { "NETWORK_TYPE_MQTT_1", "TELEMETRY__NETWORK_TYPE__NETWORK_TYPE_MQTT_1", 1 },
  { "NETWORK_TYPE_LORAWAN_1", "TELEMETRY__NETWORK_TYPE__NETWORK_TYPE_LORAWAN_1", 2 },
  { "NETWORK_TYPE_LORAWAN_2", "TELEMETRY__NETWORK_TYPE__NETWORK_TYPE_LORAWAN_2", 3 },
  { "NETWORK_TYPE_LORAWAN_3", "TELEMETRY__NETWORK_TYPE__NETWORK_TYPE_LORAWAN_3", 4 },
};
static const ProtobufCIntRange telemetry__network_type__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex telemetry__network_type__enum_values_by_name[5] =
{
  { "NETWORK_TYPE_LORAWAN_1", 2 },
  { "NETWORK_TYPE_LORAWAN_2", 3 },
  { "NETWORK_TYPE_LORAWAN_3", 4 },
  { "NETWORK_TYPE_MQTT_1", 1 },
  { "NETWORK_TYPE_UNSPECIFIED", 0 },
};
const ProtobufCEnumDescriptor telemetry__network_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "telemetry.NetworkType",
  "NetworkType",
  "Telemetry__NetworkType",
  "telemetry",
  5,
  telemetry__network_type__enum_values_by_number,
  5,
  telemetry__network_type__enum_values_by_name,
  1,
  telemetry__network_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue telemetry__severity__enum_values_by_number[3] =
{
  { "SEVERITY_UNSPECIFIED", "TELEMETRY__SEVERITY__SEVERITY_UNSPECIFIED", 0 },
  { "SEVERITY_LOW", "TELEMETRY__SEVERITY__SEVERITY_LOW", 1 },
  { "SEVERITY_HIGH", "TELEMETRY__SEVERITY__SEVERITY_HIGH", 2 },
};
static const ProtobufCIntRange telemetry__severity__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex telemetry__severity__enum_values_by_name[3] =
{
  { "SEVERITY_HIGH", 2 },
  { "SEVERITY_LOW", 1 },
  { "SEVERITY_UNSPECIFIED", 0 },
};
const ProtobufCEnumDescriptor telemetry__severity__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "telemetry.Severity",
  "Severity",
  "Telemetry__Severity",
  "telemetry",
  3,
  telemetry__severity__enum_values_by_number,
  3,
  telemetry__severity__enum_values_by_name,
  1,
  telemetry__severity__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
