/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: projects/concentradora/concentradora.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "projects/concentradora/concentradora.pb-c.h"
static const ProtobufCEnumValue projects__concentradora__alert__enum_values_by_number[6] =
{
  { "ALERT_UNSPECIFIED", "PROJECTS__CONCENTRADORA__ALERT__ALERT_UNSPECIFIED", 0 },
  { "ALERT_NO_VOLTAGE", "PROJECTS__CONCENTRADORA__ALERT__ALERT_NO_VOLTAGE", 1 },
  { "ALERT_LOW_VOLTAGE", "PROJECTS__CONCENTRADORA__ALERT__ALERT_LOW_VOLTAGE", 2 },
  { "ALERT_HIGH_VOLTAGE", "PROJECTS__CONCENTRADORA__ALERT__ALERT_HIGH_VOLTAGE", 3 },
  { "ALERT_HIGH_INTERNAL_TEMPERATURE", "PROJECTS__CONCENTRADORA__ALERT__ALERT_HIGH_INTERNAL_TEMPERATURE", 4 },
  { "ALERT_HIGH_EXTERNAL_TEMPERATURE", "PROJECTS__CONCENTRADORA__ALERT__ALERT_HIGH_EXTERNAL_TEMPERATURE", 5 },
};
static const ProtobufCIntRange projects__concentradora__alert__value_ranges[] = {
{0, 0},{0, 6}
};
static const ProtobufCEnumValueIndex projects__concentradora__alert__enum_values_by_name[6] =
{
  { "ALERT_HIGH_EXTERNAL_TEMPERATURE", 5 },
  { "ALERT_HIGH_INTERNAL_TEMPERATURE", 4 },
  { "ALERT_HIGH_VOLTAGE", 3 },
  { "ALERT_LOW_VOLTAGE", 2 },
  { "ALERT_NO_VOLTAGE", 1 },
  { "ALERT_UNSPECIFIED", 0 },
};
const ProtobufCEnumDescriptor projects__concentradora__alert__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "projects.concentradora.Alert",
  "Alert",
  "Projects__Concentradora__Alert",
  "projects.concentradora",
  6,
  projects__concentradora__alert__enum_values_by_number,
  6,
  projects__concentradora__alert__enum_values_by_name,
  1,
  projects__concentradora__alert__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
