/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: projects/fotocelula/fotocelula.proto */

#ifndef PROTOBUF_C_projects_2ffotocelula_2ffotocelula_2eproto__INCLUDED
#define PROTOBUF_C_projects_2ffotocelula_2ffotocelula_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif




/* --- enums --- */

typedef enum _Projects__Fotocelula__Resource {
  PROJECTS__FOTOCELULA__RESOURCE__RESOURCE_UNSPECIFIED = 0,
  PROJECTS__FOTOCELULA__RESOURCE__RESOURCE_FACTORY_RESET = 1,
  PROJECTS__FOTOCELULA__RESOURCE__RESOURCE_SET_LIGHT = 2,
  PROJECTS__FOTOCELULA__RESOURCE__RESOURCE_SET_DEFAULT_BRIGHTNESS = 3,
  PROJECTS__FOTOCELULA__RESOURCE__RESOURCE_BRIGHTNESS_SCHEDULE = 4,
  PROJECTS__FOTOCELULA__RESOURCE__RESOURCE_CLEAR_BRIGHTNESS_SCHEDULE = 5,
  PROJECTS__FOTOCELULA__RESOURCE__RESOURCE_CLEAR_ALL_BRIGHTNESS_SCHEDULES = 6,
  PROJECTS__FOTOCELULA__RESOURCE__RESOURCE_SET_MANUAL_MODE = 7,
  PROJECTS__FOTOCELULA__RESOURCE__RESOURCE_SET_UPLINK_FREQUENCY = 8,
  PROJECTS__FOTOCELULA__RESOURCE__RESOURCE_SET_NAME = 9,
  PROJECTS__FOTOCELULA__RESOURCE__RESOURCE_REBOOT = 10
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(PROJECTS__FOTOCELULA__RESOURCE)
} Projects__Fotocelula__Resource;
typedef enum _Projects__Fotocelula__Alert {
  PROJECTS__FOTOCELULA__ALERT__ALERT_UNSPECIFIED = 0,
  PROJECTS__FOTOCELULA__ALERT__ALERT_UNEXPECTED_LIGHT_ON = 1,
  PROJECTS__FOTOCELULA__ALERT__ALERT_UNEXPECTED_LIGHT_OFF = 2,
  PROJECTS__FOTOCELULA__ALERT__ALERT_FLASHING_LIGHT = 3,
  PROJECTS__FOTOCELULA__ALERT__ALERT_LOW_POWER = 4,
  PROJECTS__FOTOCELULA__ALERT__ALERT_LOW_VOLTAGE = 5,
  PROJECTS__FOTOCELULA__ALERT__ALERT_HIGH_VOLTAGE = 6,
  PROJECTS__FOTOCELULA__ALERT__ALERT_POWER_OUTAGE = 7
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(PROJECTS__FOTOCELULA__ALERT)
} Projects__Fotocelula__Alert;

/* --- messages --- */

/* --- per-message closures --- */


/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    projects__fotocelula__resource__descriptor;
extern const ProtobufCEnumDescriptor    projects__fotocelula__alert__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_projects_2ffotocelula_2ffotocelula_2eproto__INCLUDED */
