/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: projects/fotocelula/fotocelula.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "projects/fotocelula/fotocelula.pb-c.h"
static const ProtobufCEnumValue projects__fotocelula__resource__enum_values_by_number[11] =
{
  { "RESOURCE_UNSPECIFIED", "PROJECTS__FOTOCELULA__RESOURCE__RESOURCE_UNSPECIFIED", 0 },
  { "RESOURCE_FACTORY_RESET", "PROJECTS__FOTOCELULA__RESOURCE__RESOURCE_FACTORY_RESET", 1 },
  { "RESOURCE_SET_LIGHT", "PROJECTS__FOTOCELULA__RESOURCE__RESOURCE_SET_LIGHT", 2 },
  { "RESOURCE_SET_DEFAULT_BRIGHTNESS", "PROJECTS__FOTOCELULA__RESOURCE__RESOURCE_SET_DEFAULT_BRIGHTNESS", 3 },
  { "RESOURCE_BRIGHTNESS_SCHEDULE", "PROJECTS__FOTOCELULA__RESOURCE__RESOURCE_BRIGHTNESS_SCHEDULE", 4 },
  { "RESOURCE_CLEAR_BRIGHTNESS_SCHEDULE", "PROJECTS__FOTOCELULA__RESOURCE__RESOURCE_CLEAR_BRIGHTNESS_SCHEDULE", 5 },
  { "RESOURCE_CLEAR_ALL_BRIGHTNESS_SCHEDULES", "PROJECTS__FOTOCELULA__RESOURCE__RESOURCE_CLEAR_ALL_BRIGHTNESS_SCHEDULES", 6 },
  { "RESOURCE_SET_MANUAL_MODE", "PROJECTS__FOTOCELULA__RESOURCE__RESOURCE_SET_MANUAL_MODE", 7 },
  { "RESOURCE_SET_UPLINK_FREQUENCY", "PROJECTS__FOTOCELULA__RESOURCE__RESOURCE_SET_UPLINK_FREQUENCY", 8 },
  { "RESOURCE_SET_NAME", "PROJECTS__FOTOCELULA__RESOURCE__RESOURCE_SET_NAME", 9 },
  { "RESOURCE_REBOOT", "PROJECTS__FOTOCELULA__RESOURCE__RESOURCE_REBOOT", 10 },
};
static const ProtobufCIntRange projects__fotocelula__resource__value_ranges[] = {
{0, 0},{0, 11}
};
static const ProtobufCEnumValueIndex projects__fotocelula__resource__enum_values_by_name[11] =
{
  { "RESOURCE_BRIGHTNESS_SCHEDULE", 4 },
  { "RESOURCE_CLEAR_ALL_BRIGHTNESS_SCHEDULES", 6 },
  { "RESOURCE_CLEAR_BRIGHTNESS_SCHEDULE", 5 },
  { "RESOURCE_FACTORY_RESET", 1 },
  { "RESOURCE_REBOOT", 10 },
  { "RESOURCE_SET_DEFAULT_BRIGHTNESS", 3 },
  { "RESOURCE_SET_LIGHT", 2 },
  { "RESOURCE_SET_MANUAL_MODE", 7 },
  { "RESOURCE_SET_NAME", 9 },
  { "RESOURCE_SET_UPLINK_FREQUENCY", 8 },
  { "RESOURCE_UNSPECIFIED", 0 },
};
const ProtobufCEnumDescriptor projects__fotocelula__resource__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "projects.fotocelula.Resource",
  "Resource",
  "Projects__Fotocelula__Resource",
  "projects.fotocelula",
  11,
  projects__fotocelula__resource__enum_values_by_number,
  11,
  projects__fotocelula__resource__enum_values_by_name,
  1,
  projects__fotocelula__resource__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue projects__fotocelula__alert__enum_values_by_number[8] =
{
  { "ALERT_UNSPECIFIED", "PROJECTS__FOTOCELULA__ALERT__ALERT_UNSPECIFIED", 0 },
  { "ALERT_UNEXPECTED_LIGHT_ON", "PROJECTS__FOTOCELULA__ALERT__ALERT_UNEXPECTED_LIGHT_ON", 1 },
  { "ALERT_UNEXPECTED_LIGHT_OFF", "PROJECTS__FOTOCELULA__ALERT__ALERT_UNEXPECTED_LIGHT_OFF", 2 },
  { "ALERT_FLASHING_LIGHT", "PROJECTS__FOTOCELULA__ALERT__ALERT_FLASHING_LIGHT", 3 },
  { "ALERT_LOW_POWER", "PROJECTS__FOTOCELULA__ALERT__ALERT_LOW_POWER", 4 },
  { "ALERT_LOW_VOLTAGE", "PROJECTS__FOTOCELULA__ALERT__ALERT_LOW_VOLTAGE", 5 },
  { "ALERT_HIGH_VOLTAGE", "PROJECTS__FOTOCELULA__ALERT__ALERT_HIGH_VOLTAGE", 6 },
  { "ALERT_POWER_OUTAGE", "PROJECTS__FOTOCELULA__ALERT__ALERT_POWER_OUTAGE", 7 },
};
static const ProtobufCIntRange projects__fotocelula__alert__value_ranges[] = {
{0, 0},{0, 8}
};
static const ProtobufCEnumValueIndex projects__fotocelula__alert__enum_values_by_name[8] =
{
  { "ALERT_FLASHING_LIGHT", 3 },
  { "ALERT_HIGH_VOLTAGE", 6 },
  { "ALERT_LOW_POWER", 4 },
  { "ALERT_LOW_VOLTAGE", 5 },
  { "ALERT_POWER_OUTAGE", 7 },
  { "ALERT_UNEXPECTED_LIGHT_OFF", 2 },
  { "ALERT_UNEXPECTED_LIGHT_ON", 1 },
  { "ALERT_UNSPECIFIED", 0 },
};
const ProtobufCEnumDescriptor projects__fotocelula__alert__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "projects.fotocelula.Alert",
  "Alert",
  "Projects__Fotocelula__Alert",
  "projects.fotocelula",
  8,
  projects__fotocelula__alert__enum_values_by_number,
  8,
  projects__fotocelula__alert__enum_values_by_name,
  1,
  projects__fotocelula__alert__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
