/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: command/command.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "command/command.pb-c.h"
void   command__trigger__init
                     (Command__Trigger         *message)
{
  static const Command__Trigger init_value = COMMAND__TRIGGER__INIT;
  *message = init_value;
}
size_t command__trigger__get_packed_size
                     (const Command__Trigger *message)
{
  assert(message->base.descriptor == &command__trigger__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t command__trigger__pack
                     (const Command__Trigger *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &command__trigger__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t command__trigger__pack_to_buffer
                     (const Command__Trigger *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &command__trigger__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Command__Trigger *
       command__trigger__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Command__Trigger *)
     protobuf_c_message_unpack (&command__trigger__descriptor,
                                allocator, len, data);
}
void   command__trigger__free_unpacked
                     (Command__Trigger *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &command__trigger__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   command__command__init
                     (Command__Command         *message)
{
  static const Command__Command init_value = COMMAND__COMMAND__INIT;
  *message = init_value;
}
size_t command__command__get_packed_size
                     (const Command__Command *message)
{
  assert(message->base.descriptor == &command__command__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t command__command__pack
                     (const Command__Command *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &command__command__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t command__command__pack_to_buffer
                     (const Command__Command *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &command__command__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Command__Command *
       command__command__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Command__Command *)
     protobuf_c_message_unpack (&command__command__descriptor,
                                allocator, len, data);
}
void   command__command__free_unpacked
                     (Command__Command *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &command__command__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   command__command_pack__init
                     (Command__CommandPack         *message)
{
  static const Command__CommandPack init_value = COMMAND__COMMAND_PACK__INIT;
  *message = init_value;
}
size_t command__command_pack__get_packed_size
                     (const Command__CommandPack *message)
{
  assert(message->base.descriptor == &command__command_pack__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t command__command_pack__pack
                     (const Command__CommandPack *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &command__command_pack__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t command__command_pack__pack_to_buffer
                     (const Command__CommandPack *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &command__command_pack__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Command__CommandPack *
       command__command_pack__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Command__CommandPack *)
     protobuf_c_message_unpack (&command__command_pack__descriptor,
                                allocator, len, data);
}
void   command__command_pack__free_unpacked
                     (Command__CommandPack *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &command__command_pack__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor command__trigger__field_descriptors[4] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Command__Trigger, type),
    &command__trigger_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Command__Trigger, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "range",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Command__Trigger, n_range),
    offsetof(Command__Trigger, range),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "measurement",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Command__Trigger, measurement),
    &telemetry__measurement__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned command__trigger__field_indices_by_name[] = {
  3,   /* field[3] = measurement */
  2,   /* field[2] = range */
  0,   /* field[0] = type */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange command__trigger__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor command__trigger__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "command.Trigger",
  "Trigger",
  "Command__Trigger",
  "command",
  sizeof(Command__Trigger),
  4,
  command__trigger__field_descriptors,
  command__trigger__field_indices_by_name,
  1,  command__trigger__number_ranges,
  (ProtobufCMessageInit) command__trigger__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor command__command__field_descriptors[9] =
{
  {
    "resource_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Command__Command, resource_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Command__Command, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "string_value",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Command__Command, string_value),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bool_value",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Command__Command, bool_value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data_value",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Command__Command, data_value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "unit",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Command__Command, unit),
    &telemetry__unit__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "trigger",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Command__Command, trigger),
    &command__trigger__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cron",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Command__Command, cron),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "duration",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Command__Command, duration),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned command__command__field_indices_by_name[] = {
  3,   /* field[3] = bool_value */
  7,   /* field[7] = cron */
  4,   /* field[4] = data_value */
  8,   /* field[8] = duration */
  0,   /* field[0] = resource_id */
  2,   /* field[2] = string_value */
  6,   /* field[6] = trigger */
  5,   /* field[5] = unit */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange command__command__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor command__command__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "command.Command",
  "Command",
  "Command__Command",
  "command",
  sizeof(Command__Command),
  9,
  command__command__field_descriptors,
  command__command__field_indices_by_name,
  1,  command__command__number_ranges,
  (ProtobufCMessageInit) command__command__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor command__command_pack__field_descriptors[1] =
{
  {
    "commands",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Command__CommandPack, n_commands),
    offsetof(Command__CommandPack, commands),
    &command__command__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned command__command_pack__field_indices_by_name[] = {
  0,   /* field[0] = commands */
};
static const ProtobufCIntRange command__command_pack__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor command__command_pack__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "command.CommandPack",
  "CommandPack",
  "Command__CommandPack",
  "command",
  sizeof(Command__CommandPack),
  1,
  command__command_pack__field_descriptors,
  command__command_pack__field_indices_by_name,
  1,  command__command_pack__number_ranges,
  (ProtobufCMessageInit) command__command_pack__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue command__trigger_type__enum_values_by_number[6] =
{
  { "TRIGGER_TYPE_UNSPECIFIED", "COMMAND__TRIGGER_TYPE__TRIGGER_TYPE_UNSPECIFIED", 0 },
  { "TRIGGER_TYPE_VALUE", "COMMAND__TRIGGER_TYPE__TRIGGER_TYPE_VALUE", 1 },
  { "TRIGGER_TYPE_GREATER_THAN_OR_EQUAL", "COMMAND__TRIGGER_TYPE__TRIGGER_TYPE_GREATER_THAN_OR_EQUAL", 2 },
  { "TRIGGER_TYPE_LESS_THAN_OR_EQUAL", "COMMAND__TRIGGER_TYPE__TRIGGER_TYPE_LESS_THAN_OR_EQUAL", 3 },
  { "TRIGGER_TYPE_DELTA", "COMMAND__TRIGGER_TYPE__TRIGGER_TYPE_DELTA", 4 },
  { "TRIGGER_TYPE_RANGE", "COMMAND__TRIGGER_TYPE__TRIGGER_TYPE_RANGE", 5 },
};
static const ProtobufCIntRange command__trigger_type__value_ranges[] = {
{0, 0},{0, 6}
};
static const ProtobufCEnumValueIndex command__trigger_type__enum_values_by_name[8] =
{
  { "TRIGGER_TYPE_DELTA", 4 },
  { "TRIGGER_TYPE_GREATER_THAN_OR_EQUAL", 2 },
  { "TRIGGER_TYPE_LESS_THAN_OR_EQUAL", 3 },
  { "TRIGGER_TYPE_MAX", 3 },
  { "TRIGGER_TYPE_MIN", 2 },
  { "TRIGGER_TYPE_RANGE", 5 },
  { "TRIGGER_TYPE_UNSPECIFIED", 0 },
  { "TRIGGER_TYPE_VALUE", 1 },
};
const ProtobufCEnumDescriptor command__trigger_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "command.TriggerType",
  "TriggerType",
  "Command__TriggerType",
  "command",
  6,
  command__trigger_type__enum_values_by_number,
  8,
  command__trigger_type__enum_values_by_name,
  1,
  command__trigger_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
